apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeappdeployment
  labels:
    app: nodeapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - name: nodeapp
        image: kammana/nodeapp:v2
        ports:
        - containerPort: 8080

